### ISSUE TITLE
 Expception: Driver in Add-on was not able to get connected!

### ISSUE THREAD

**Issue by jouster1974** [fuatakgun/eufy_security#344]
Quite often, when checking HomeAssistant, the latest grabs from cameras will show as grey boxes...but upon looking into the integration, it will show the integration as below

Expception: Driver in Add-on was not able to get connected!

Quite often a simple HA restart will fix it, although on every other occasion the above error shows and a further restart is required

I was therefore wondering if there is anything I should be tweaking to fix this issue.~

Everything else works really well for me including the Security panel, door and motion sensors etc so just hoping to nail down this last part

Ironically, now having the issue at every restart and reboot and cannot see the grabs at all

seeing a number of errors

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/coordinator.py:388
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 12:04:21 (15 occurrences)
Last logged: 12:04:22

eufy_security - Event received but device is missing, maybe not connected\

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/coordinator.py:184
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 12:04:20 (1 occurrences)
Last logged: 12:04:20

Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
    if await self.async_get_device_properties() is False:
  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/coordinator.py:388
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 12:04:21 (15 occurrences)
Last logged: 12:04:22

eufy_security - Event received but device is missing, maybe not connected

Nothing else has changed at my end and who system is available via app as usual

**Comment by superpower10** [comment]
Same here

**Comment by jouster1974** [comment]
glad its not just me.....was wondering if Id done something daft but Iven changed nothing

**Comment by jouster1974** [comment]
latest update this evening seems to have fixed it after install and restart

**Comment by superpower10** [comment]
What Update? Are you talking about a beta or a final?

**Comment by Morteum9** [comment]
Same issues here, have seen the cameras still provide the motion sensing needed for other automations but no video feeds on my dashboard with this same error since the update to 2.2.6

[Eufy_Security_2.2.6_Log.txt](https://github.com/fuatakgun/eufy_security/files/8763422/Eufy_Security_2.2.6_Log.txt)

**Comment by Morteum9** [comment]
Further proved this by rolling back to 2.2.4, no more camera loading issues. Guess I'll just hold off on updating for a while

**Comment by fuatakgun** [comment]
please retest with latest version and comment back here
