### ISSUE TITLE
error event recived but device is missing 

### ISSUE THREAD

**Issue by volzb** [fuatakgun/eufy_security#285]
**Describe the bug**
I have been using the integration for a few weeks now and it was working but now I'm getting the error below.
I have tried disabling/enabling and power cycles but no luck. Any idea what could be causing it, I a bit lost where to look next?

i have 4 cameras and one base, ever think seems to be working in the Eufy app and i haven't noticed and loss of devices.

**To Reproduce**
The error seems to always be present.

**Expected behavior**
Some help would be awesome to locate and fix the issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/6599352/155078899-03f44473-65d9-441d-84ab-89288ef1e1d7.png)

**Hardware Information about Home Assistant**
home-assistant OS 7.4  supervisor 2022.01.1
running in a VM on a Lenovo think center 

**Hardware Information about Cameras**
Eufy 2 cam pro

**Comment by jeroenvdd** [comment]
Mine was working fine too, did a reboot after updating to 7.4 and now I get the exact error you are refering too

**Comment by jeroenvdd** [comment]
https://github.com/fuatakgun/eufy_security/issues/280 seems to be the same

**Comment by jeroenvdd** [comment]
- after update to latest HA / eufy its back up in my case

**Comment by fuatakgun** [comment]
this should happen in first install, sometimes we are not able to receive all device specific information at expected time, even though events are receiving. Reinstalling the integration should eliminate this.

**Comment by sunnyd24** [comment]
@fuatakgun This happened today when I updated the haos to 8.0 and refused to start any camera cards until I did a Dev Tools restart from YAML tab.

Suggest adding in some delay check (not sure what it needs before this error will resolve, waiting on port 3000 on localhost) before attempting to start up cards or adding a start-up delay option in the cards?

"Retrying in background" doesn't seem to fix this issue.

See below for log entries:
```
2022-05-16 22:03:29 WARNING (MainThread) [homeassistant.config_entries] Config entry 'localhost' for eufy_security integration not ready yet: Exception: Host/port is not reachable localhost 3000!; Retrying in background
.......
2022-05-16 22:03:47 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
    if await self.async_get_device_properties() is False:
  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
2022-05-16 22:03:49 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Event received but device is missing, maybe not connected
```

**Comment by superpower10** [comment]
Same here. Even after Update to the newest Eufy Integration

**Comment by fuatakgun** [comment]
delay was introduced by one PRs, this should be resolved
