### ISSUE TITLE
8.0.4 does not run on HA < 2024.11

### ISSUE THREAD

**Issue by luuuis** [fuatakgun/eufy_security#1257]
**Describe the bug**

Release 8.0.4 and newer do not work on HA < 2024.11 due to a dependency on the newly-introduced `AlarmControlPanelState` enum introduced in #1240.

**To reproduce**

1. Upgrade to version 8.0.4 or newer while running  HA 2024.10.4.
2. Restart HA.

The error is:
```
ImportError: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel'
```

<details>
<summary>Expand for full stack trace</summary>

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 26 November 2024 at 12:28:01 (1 occurrences)
Last logged: 26 November 2024 at 12:28:01

Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 56, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2147, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 7 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/eufy_security/alarm_control_panel.py", line 6, in <module>
    from homeassistant.components.alarm_control_panel import (
ImportError: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py)
```
</details>

**Expected behavior**

The component should work on a HA version that was released barely 1 month ago (2024.10.4 was released on October 25).

Since the enum was only just introduced in https://github.com/home-assistant/core/pull/126283 and will be removed in 2025.11 don't you feel it's a bit premature to introduce this breaking change just because of a deprecation warning? Not everyone is on the bleeding edge all the time with HA.

**Suggested fix**

If it's too much to live with a warning in logs for a few months then it is possible in code to test if the enum exists and use it if so, falling back to the deprecated constants otherwise. This would be removed closer to the deprecation cut-off.

Alternatively, simpler but not as good for users: in `hacs.json` it is possible to [indicate the minimum required HA version with the `homeassistant` property](https://hacs.xyz/docs/publish/start/#hacsjson). Setting a value there would at least prevent users from shooting themselves in the foot by upgrading to a version that is incompatible. The breaking change should also be indicated in release notes.

**Comment by va2na** [comment]
Since latest HA update i lost my door lock

**Comment by va2na** [comment]
2024-12-16 08:53:31.545 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 08:53:31.546 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 08:53:31.547 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration toyota_na which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 08:53:31.547 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration govee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 08:53:31.548 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 08:53:31.548 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-16 08:53:33.845 ERROR (MainThread) [homeassistant.config] Unknown error when validating config for sensor from integration template - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1074, in _async_load_and_validate_platform_integration
    return platform.PLATFORM_SCHEMA(p_integration.config)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^

**Comment by dankauk** [comment]
> Since latest HA update i lost my door lock

I have same issue.

**Comment by omar10wahab** [comment]
Are you guys seeing the devices at all? I had initial issue of nothing showing up but when I updated HA and eufy integration it started to show my doorbell and door lock. I just recently noticed the states don't update with values. Not sure if anyone else is having this issue
